#!/usr/bin/env python3
# SPDX-FileCopyrightText: (c) 2025-2026 Tenstorrent USA, Inc.
# SPDX-License-Identifier: Apache-2.0

# Embed a prebuilt firmware binary as a C array named "<binary-stem>_blob"
import argparse
import os

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--bin', required=True)
    parser.add_argument('--out', required=True)
    args = parser.parse_args()

    name = os.path.splitext(os.path.basename(args.bin))[0] + '_blob'
    with open(args.bin, 'rb') as f:
        blob = f.read()

    lines = [
        f'// Generated by gen_fw_blob.py from {os.path.basename(args.bin)} -- do not edit.',
        '#pragma once',
        '#include <stdint.h>',
        f'static constexpr uint8_t {name}[] = {{',
    ]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append('    ' + ' '.join(f'0x{b:02x},' for b in chunk))
    lines.append('};')
    with open(args.out, 'w') as f:
        f.write('\n'.join(lines) + '\n')

if __name__ == '__main__':
    main()
